# Generated by Django 5.1.2 on 2025-05-30 08:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributing_factor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Incident_Evidence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='evidence')),
            ],
        ),
        migrations.CreateModel(
            name='Potential_severity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recurrency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Risk_level',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25, null=True)),
                ('last_name', models.CharField(max_length=25, null=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('dep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=30)),
                ('phone_no', models.CharField(max_length=10)),
                ('designation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.designation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Department_poc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_pocc', to='api.department')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Follow_up_action',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action_description', models.CharField(max_length=500)),
                ('date_completed', models.DateTimeField()),
                ('responsible_employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Immediate_actions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=500)),
                ('action_taken_by', models.ManyToManyField(db_table='Immediate_action_employee', related_name='action_employee', to='api.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Improvement_Recommendation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action_description', models.CharField(max_length=500)),
                ('responsible_employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Incident_Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('occurence_date', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=100)),
                ('Follow_up', models.ManyToManyField(related_name='follow_up_tickets', through='api.Follow_up_action', to='api.employee')),
                ('ImmediateActions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_taken', to='api.immediate_actions')),
                ('Improvement_recommendations', models.ManyToManyField(related_name='Improvements', through='api.Improvement_Recommendation', to='api.employee')),
                ('Individuals_invloved', models.ManyToManyField(db_table='Individuals_involved', related_name='individuals_involved', to='api.employee')),
                ('Witnesses', models.ManyToManyField(db_table='Incident_witness', related_name='witness', to='api.employee')),
                ('assigned_POC', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.department_poc')),
                ('contributing_factors', models.ManyToManyField(db_table='Incident_factor', to='api.contributing_factor')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department')),
                ('evidence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.incident_evidence')),
                ('requestor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Incident_status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('incident_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.incident_ticket')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.status')),
            ],
        ),
        migrations.AddField(
            model_name='incident_evidence',
            name='incident_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.incident_ticket'),
        ),
        migrations.AddField(
            model_name='improvement_recommendation',
            name='incident_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.incident_ticket'),
        ),
        migrations.AddField(
            model_name='immediate_actions',
            name='incident_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.incident_ticket'),
        ),
        migrations.AddField(
            model_name='follow_up_action',
            name='incident_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.incident_ticket'),
        ),
        migrations.CreateModel(
            name='Incident_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department')),
            ],
        ),
        migrations.AddField(
            model_name='incident_ticket',
            name='report_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.incident_type'),
        ),
        migrations.CreateModel(
            name='Risk_assessment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recurrency')),
                ('severity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.potential_severity')),
                ('risk_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.risk_level')),
            ],
        ),
        migrations.AddField(
            model_name='incident_ticket',
            name='Risk_assessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.risk_assessment'),
        ),
        migrations.CreateModel(
            name='Stake_holder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='incident_ticket',
            name='status',
            field=models.ManyToManyField(related_name='ticket_status', through='api.Incident_status', to='api.status'),
        ),
    ]
