# Generated by Django 5.1.2 on 2025-05-28 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident_Evidence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='evidence')),
                ('incident_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.incident_ticket')),
            ],
        ),
    ]
