# Generated by Django 5.1.2 on 2025-06-03 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immediate_actions',
            name='incident_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Immediateactions', to='api.incident_ticket'),
        ),
    ]
