# Generated by Django 5.1.2 on 2025-05-28 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_status_status_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Potential_severity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recurrency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Risk_level',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Risk_assessment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recurrency')),
                ('severity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.potential_severity')),
                ('risk_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.risk_level')),
            ],
        ),
    ]
