# Generated by Django 5.1.2 on 2025-06-04 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_immediate_actions_incident_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident_ticket',
            name='ImmediateActions',
        ),
        migrations.RemoveField(
            model_name='incident_ticket',
            name='evidence',
        ),
    ]
