# Generated by Django 5.1.2 on 2025-05-28 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_potential_severity_recurrency_risk_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
