# Generated by Django 5.1.2 on 2025-06-04 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_incident_ticket_immediateactions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident_evidence',
            name='incident_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_evidences', to='api.incident_ticket'),
        ),
        migrations.AlterField(
            model_name='incident_ticket',
            name='Individuals_invloved',
            field=models.ManyToManyField(blank=True, db_table='Individuals_involved', related_name='individuals_involved', to='api.employee'),
        ),
        migrations.AlterField(
            model_name='incident_ticket',
            name='Witnesses',
            field=models.ManyToManyField(blank=True, db_table='Incident_witness', related_name='witness', to='api.employee'),
        ),
        migrations.AlterField(
            model_name='incident_ticket',
            name='contributing_factors',
            field=models.ManyToManyField(blank=True, db_table='Incident_factor', to='api.contributing_factor'),
        ),
    ]
