# Generated by Django 5.1.2 on 2025-06-05 09:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_incident_evidence_incident_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='improvement_recommendation',
            name='incident_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Improvement_Recommendation', to='api.incident_ticket'),
        ),
        migrations.AlterField(
            model_name='incident_status',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='incident_status',
            name='incident_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_status', to='api.incident_ticket'),
        ),
    ]
