# Generated by Django 5.1.2 on 2025-06-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_improvement_recommendation_incident_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow_up_action',
            name='date_completed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
