# Generated by Django 5.1.2 on 2025-05-28 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_role_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
