# Generated by Django 5.1.2 on 2025-06-16 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_follow_up_action_date_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident_ticket',
            name='Risk_assessment',
        ),
        migrations.AddField(
            model_name='incident_ticket',
            name='Potential_severity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.potential_severity'),
        ),
        migrations.AddField(
            model_name='incident_ticket',
            name='recurrency',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.recurrency'),
        ),
        migrations.AddField(
            model_name='incident_ticket',
            name='risk_level',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.risk_level'),
        ),
        migrations.DeleteModel(
            name='Risk_assessment',
        ),
    ]
