# Generated by Django 5.1.2 on 2025-05-28 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_customuser_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
