# Generated by Django 5.1.2 on 2025-06-18 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_incident_ticket_risk_assessment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow_up_action',
            name='incident_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up', to='api.incident_ticket'),
        ),
    ]
