# Generated by Django 5.1.2 on 2025-05-28 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident_ticket',
            name='evidence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.incident_evidence'),
        ),
    ]
