# Generated by Django 5.1.2 on 2025-05-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_incident_ticket_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident_ticket',
            name='contributing_factors',
            field=models.ManyToManyField(through='api.Incident_factor', to='api.contributing_factor'),
        ),
    ]
