# Generated by Django 5.1.2 on 2025-05-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_incident_ticket_contributing_factors'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident_ticket',
            name='Individuals_invloved',
            field=models.ManyToManyField(db_table='Individuals_involved', null=True, related_name='individuals_involved', to='api.employee'),
        ),
    ]
