# Generated by Django 5.1.2 on 2025-05-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_incident_ticket_individuals_invloved'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident_ticket',
            name='Witnesses',
            field=models.ManyToManyField(db_table='Incident_witness', null=True, related_name='witness', to='api.employee'),
        ),
    ]
