# Generated by Django 5.1.2 on 2025-05-29 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_incident_ticket_witnesses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Immediate_action_employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Immediate_actions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=500)),
                ('action_taken_by', models.ManyToManyField(through='api.Immediate_action_employee', to='api.employee')),
            ],
        ),
        migrations.AddField(
            model_name='immediate_action_employee',
            name='immediate_action_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.immediate_actions'),
        ),
    ]
