# Generated by Django 5.1.2 on 2025-05-29 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_immediate_action_employee_immediate_actions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='immediate_actions',
            name='incident_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.incident_ticket'),
        ),
        migrations.AddField(
            model_name='incident_ticket',
            name='Action_taken',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_taken', to='api.immediate_actions'),
        ),
        migrations.AlterField(
            model_name='immediate_actions',
            name='action_taken_by',
            field=models.ManyToManyField(related_name='action_employee', through='api.Immediate_action_employee', to='api.employee'),
        ),
    ]
