# Generated by Django 5.1.2 on 2025-05-29 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_immediate_actions_incident_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident_ticket',
            name='Risk_assessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.risk_assessment'),
        ),
    ]
