# Generated by Django 5.1.2 on 2025-05-29 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_incident_ticket_risk_assessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Improvement_Recommendation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action_description', models.CharField(max_length=500)),
                ('incident_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.incident_ticket')),
                ('responsible_employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
        ),
    ]
