# Generated by Django 5.1.2 on 2025-05-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_improvement_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident_ticket',
            name='Improvement_recommendation',
            field=models.ManyToManyField(null=True, related_name='Improvements', through='api.Improvement_Recommendation', to='api.employee'),
        ),
    ]
