# Generated by Django 5.1.2 on 2025-05-29 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_incident_ticket_improvement_recommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow_up_action',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action_description', models.CharField(max_length=500)),
                ('date_completed', models.DateTimeField()),
                ('incident_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.incident_ticket')),
                ('responsible_employee_id', models.ManyToManyField(db_table='Follow_up_taken_by', to='api.employee')),
            ],
        ),
    ]
