# Generated by Django 5.1.2 on 2025-05-29 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_follow_up_action'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow_up_action',
        ),
    ]
