# Generated by Django 5.1.2 on 2025-05-29 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_delete_follow_up_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident_ticket',
            old_name='Improvement_recommendation',
            new_name='Improvement_recommendations',
        ),
    ]
