# Generated by Django 5.1.2 on 2025-05-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_improvement_recommendation_incident_ticket_improvement_recommendations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident_ticket',
            name='Improvement_recommendations',
            field=models.ManyToManyField(related_name='Improvements', through='api.Improvement_Recommendation', to='api.employee'),
        ),
    ]
