# Generated by Django 5.1.2 on 2025-05-29 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_incident_ticket_improvement_recommendations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow_up_action',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action_description', models.CharField(max_length=500)),
                ('date_completed', models.DateTimeField()),
                ('incident_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.incident_ticket')),
                ('responsible_employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
        ),
        migrations.AddField(
            model_name='incident_ticket',
            name='Follow_up',
            field=models.ManyToManyField(null=True, related_name='follow_up_tickets', through='api.Follow_up_action', to='api.employee'),
        ),
    ]
