# Generated by Django 5.1.2 on 2025-05-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_follow_up_action_incident_ticket_follow_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident_ticket',
            name='Follow_up',
            field=models.ManyToManyField(related_name='follow_up_tickets', through='api.Follow_up_action', to='api.employee'),
        ),
    ]
