# Generated by Django 5.1.2 on 2025-05-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_incident_ticket_follow_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident_ticket',
            name='Individuals_invloved',
            field=models.ManyToManyField(db_table='Individuals_involved', related_name='individuals_involved', to='api.employee'),
        ),
        migrations.AlterField(
            model_name='incident_ticket',
            name='Witnesses',
            field=models.ManyToManyField(db_table='Incident_witness', related_name='witness', to='api.employee'),
        ),
    ]
