# Generated by Django 5.1.2 on 2025-05-29 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_incident_ticket_individuals_invloved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident_status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('incident_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.incident_ticket')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.status')),
            ],
        ),
        migrations.DeleteModel(
            name='status_time',
        ),
    ]
