# Generated by Django 5.1.2 on 2025-05-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_incident_status_delete_status_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident_ticket',
            name='status',
            field=models.ManyToManyField(related_name='ticket_status', through='api.Incident_status', to='api.status'),
        ),
    ]
