# Generated by Django 5.1.2 on 2025-05-29 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_incident_ticket_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident_ticket',
            old_name='Action_taken',
            new_name='ImmediateActions',
        ),
    ]
